import axios from 'axios'
import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState, AppThunk } from '../../app/store';
// import { fetchCount } from './counterAPI';
export interface AuthState {
  idToken: string | null,
  localId: string | null,
  error: object | null,
  isLoading: boolean,
}

const initialState: AuthState = {
  idToken: null,
  localId: null,
  error: null,
  isLoading: false,
}

// export const logout = () => {
//   localStorage.removeItem('idToken')
//   localStorage.removeItem('expirationDate')
//   localStorage.removeItem('localId')

//   return { type: types.AUTH_LOGOUT }
// }

// const checkAuthTimeout = (expiresIn: number, dispatch: Dispatch) => setTimeout(() => dispatch(logout()), expiresIn * 1000);

// export const logInMaybe = (): types.AppThunk => dispatch => {
//   const idToken = localStorage.getItem('idToken')
//   if (!idToken) return dispatch(logout())
//   const expirationDate = new Date(localStorage.getItem('expirationDate')!)
//   if (expirationDate > new Date()) {
//     dispatch(authSuccessed(localStorage.getItem('localId')!, idToken))
//     checkAuthTimeout((expirationDate.getTime() - new Date().getTime()) / 1000, dispatch)
//   } else {
//     dispatch(logout())
//   }
// }

interface ReqPayload {
  email: string,
  password: string,
  returnSecureToken: boolean
}

interface ResPayload {
  data: {
    idToken: string,
    email: string,
    refreshToken: string,
    expiresIn: string,
    localId: string,
    registered: boolean
  }
}

// export const authStarted = () => ({ type: types.AUTH_STARTED })
// export const authSuccessed = (localId: string, idToken: string) => ({ type: types.AUTH_SUCCESSED, localId, idToken })
// export const authFailed = (error: object) => ({ type: types.AUTH_FAILED, error })


export const authenticate = createAsyncThunk(
  'auth',
  async ({ email, password, returnSecureToken }: ReqPayload) => {
    const API_KEY = 'AIzaSyD77mZ0A4HPCD8-heTNpvq3nWEnOvq_qNo'
    const payload: ReqPayload = { email, password, returnSecureToken: true }
    const response: ResPayload = await axios.post(
      `https://identitytoolkit.googleapis.com/v1/accounts:${returnSecureToken ? 'signInWithPassword' : 'signUp'}?key=${API_KEY}`,
      payload
    )
    const { localId, idToken, expiresIn } = response.data
    const expirationDate = new Date(new Date().getTime() + (+expiresIn * 1000))
    localStorage.setItem('idToken', idToken)
    localStorage.setItem('localId', localId)
    localStorage.setItem('expirationDate', '' + expirationDate)

    return response.data
  }
);

// export const authenticate = ({ email, password, isLogin }: { email: string, password: string, isLogin: boolean }): types.AppThunk => async dispatch => {
//   try {
//     dispatch(authStarted())
//     const API_KEY = 'AIzaSyD77mZ0A4HPCD8-heTNpvq3nWEnOvq_qNo'
//     const payload: ReqPayload = { email, password, returnSecureToken: true }
//     const response: ResPayload = await axios.post(
//       `https://identitytoolkit.googleapis.com/v1/accounts:${isLogin ? 'signInWithPassword' : 'signUp'}?key=${API_KEY}`,
//       payload
//     )
//     const { localId, idToken, expiresIn } = response.data
//     const expirationDate = new Date(new Date().getTime() + (+expiresIn * 1000))
//     localStorage.setItem('idToken', idToken)
//     localStorage.setItem('localId', localId)
//     localStorage.setItem('expirationDate', '' + expirationDate)
//     dispatch(authSuccessed(localId, idToken))
//     checkAuthTimeout(+expiresIn, dispatch)
//   } catch (error: any) {
//     dispatch(authFailed(error.response.data.error))
//   }
// }


export const authSlice = createSlice({
  name: 'auth',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    logout: (state) => {
      localStorage.removeItem('idToken')
      localStorage.removeItem('expirationDate')
      localStorage.removeItem('localId')

      state.idToken = null
      state.localId = null
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(authenticate.pending, (state) => {
        state.isLoading = true
      })
      .addCase(authenticate.fulfilled, (state, action) => {
        state.idToken = action.payload.idToken
        state.localId = action.payload.localId
        state.error = null
        state.isLoading = false
      })
      .addCase(authenticate.rejected, (state, action) => {
        state.error = action.error
        state.isLoading = false
      })
  },
});